flags:
  triage:
    library-only: false
    dev: false

nix:
  enable: true
  packages: [zlib, git, openssh, haskell.packages.lts-3_13.happy, pcre, glpk, openssl, icu]

packages:
- '.'
- ../orgmode
- ../org-issue-sync
extra-deps: ['logging-2.2.0', 'orgmode-0.1.0.1', 'github-0.13.2', 'google-oauth2-0.2.0', 'failure-0.2.0.3']
resolver: lts-2.19
