Default: &defaults
  database: triage.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: triage_test.sqlite3
  <<: *defaults

Staging:
  database: triage_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: triage_production.sqlite3
  poolsize: 100
  <<: *defaults
